export const sessionFlowName = {
  LoginMiStory: "login",
  SsoFlow: "login",
  Reflection: "reflection",
  ListeningActivity: "listening-activity",
  ParentPerceptionSurvey: "parent_perception_survey",
  ShikshaSamvad: "shiksha-samvad",
  DelhiShikshaSamvad: "delhi-shiksha-samvad",
  StudyTeacherInterview: "study_teacher_interview",
  BiharStudentFGD: "bihar-student-fgd",
  OdishaYouth: "odisha-youth",
  OdishaYouthAI: "odisha-youth-ai",
  TelanganaPTMPilot: "telangana-ptm-pilot",
  StakeholderFGD: "stakeholder-fgd",
  CommunityFGD: "community-fgd",
  XylemX_entrepreneurship_development: "XylemX_entrepreneurship_development",
}
